### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by goodman-capu** [yconst/YCML#9]
It would be much easier to import and update the project via CocoaPods

**Comment by yconst** [comment]
Thanks for your suggestion, but I find Cocoapods to be too much trouble to maintain. I had worked earlier with Cocoapods in my other library - YCMatrix, and found myself spending considerable time debugging obscure issues introduced because of the cocoapods authoritative project management scheme. This was valuable time that could be spent in developing new features.
I think a package manager such as Carthage can be easier to maintain, and should practically come free without any additions to YCML.

**Comment by yconst** [comment]
Opened a new ticket #10 re. Carthage support
